import type { Metadata } from "next";
import Link from "next/link";
import "../marketing.css";
import { SITE_URL } from "@/lib/marketing/constants";

export const metadata: Metadata = {
  title: "Terms of Use — StudySnap",
  description: "The terms for using StudySnap, a free study companion app.",
  alternates: { canonical: `${SITE_URL}/terms` },
};

export default function TermsPage() {
  return (
    <main className="marketing-root" aria-label="StudySnap terms of use">
      <div className="marketing-legal">
        <div className="marketing-legal-inner">
          <Link href="/" className="marketing-link marketing-legal-back">
            ← Back to home
          </Link>
          <h1>Terms of Use</h1>
          <p className="marketing-legal-updated">Last updated: September 2026</p>

          <h2>The service</h2>
          <p>
            StudySnap is a free study companion: notes, voice notes, revision
            scheduling, gamification, and AI-powered study tools. It is
            provided as-is, and we may change or discontinue parts of it as
            the project evolves.
          </p>

          <h2>Your account</h2>
          <p>
            You sign in with your own account and are responsible for keeping
            it secure. Don&apos;t share accounts, and don&apos;t upload content
            you don&apos;t have the right to use.
          </p>

          <h2>AI-generated content</h2>
          <p>
            Summaries, questions, flashcards, and explanations are generated by
            AI from the material you provide. They can be wrong or incomplete —
            always verify important facts against your own study material
            before exams.
          </p>

          <h2>Acceptable use</h2>
          <p>
            Don&apos;t misuse the service: no attempts to break into other
            accounts, overload the service, or abuse AI features in ways that
            harm others. Daily AI usage limits apply so the service stays
            available for everyone.
          </p>
        </div>
      </div>
    </main>
  );
}
